### ISSUE TITLE
go vet asks us to change to change Tx{In, Out}.WriteTo signature

### ISSUE THREAD

**Issue by marten-seemann** [ipld/go-ipld-btc#24]
`go vet` says:
```
./tx.go:248:16: method WriteTo(w io.Writer) error should have signature WriteTo(io.Writer) (int64, error)
./tx.go:266:17: method WriteTo(w io.Writer) error should have signature WriteTo(io.Writer) (int64, error)
```

Unfortunately, this concerns `TxIn` and `TxOut`, which are both exported interfaces. We're therefore talking about an API change. Any thoughts, @rvagg and @mvdan?

**Comment by mvdan** [comment]
This is a v0, so we can technically make this change.

Unfortunate that we weren't running vet from the start, and there isn't a way to "ignore" that case unless we just don't run vet at all.

I lean towards doing this, because we can as per semver, and because the few downstream users should be able to easily fix up their code. I also assume that vet in CI would be merged shortly after the fix above.
